import React, {useEffect, useRef, useState} from 'react';
import {ArrowRight, ArrowLeft, ArrowUpRight, Check, CheckCircle2, Copy, Download, FileText, FolderOpen, Link2, ListChecks, Monitor, Puzzle, RotateCcw, Rocket} from 'lucide-react';
import data from '../content/agentic-practice.json';
import {STORAGE_KEY, destinationValid, fillPrompt, restoreProgress, resolveStep} from './agentic-practice-model.mjs';
import './agentic-practice.css';
import {AgenticConceptLesson, PracticeFieldRoles} from './agentic-concepts.jsx';

const steps=data.steps, ids=steps.map(s=>s.id), ROOT='/downloads/agentic-coding/';
const files={bundle:{file:'Agentic-Coding-Practice.zip',label:'기본 자료 ZIP',detail:'시작 안내 · 프롬프트 · 예시, 3개 파일'},guide:{file:'READ_ME.md',label:'시작 안내',detail:'전체 진행 순서'},prompts:{file:'PROMPTS.md',label:'프롬프트 모음',detail:'PPT와 함께 쓰는 요청문'},examples:{file:'EXAMPLES.md',label:'Skill + 입력 예시',detail:'Skill 본문과 입력 A / B'},'skill-example':{file:'SKILL-EXAMPLE.md',label:'Skill 본문 예시',detail:'설치 전 검토할 절차'},'news-result':{file:'GEEKNEWS-RESULT.json',label:'실제 피드 응답',detail:'검수 시점의 조회 기록'},'snapshot-xml':{file:'BROWSER-XML-SNAPSHOT.zip',label:'실제 XML 첨부 예제',detail:'목록 3건 · 상세 1건 · 원래 조회 시점'},'snapshot-result':{file:'HERITAGE-SNAPSHOT.json',label:'첨부 파싱 결과',detail:'partial · 상세 누락을 보존한 실제 결과'},'api-result':{file:'HERITAGE-A.json',label:'실제 API 응답',detail:'검수 시점의 경복궁 결과'},'input-a':{file:'INPUT-A.md',label:'입력 A',detail:'경복궁 · 최대 3개'},'input-b':{file:'INPUT-B.md',label:'입력 B',detail:'첨성대 · 새 호출'}};
function initial(){try{return restoreProgress(JSON.parse(localStorage.getItem(STORAGE_KEY)),ids)}catch{return restoreProgress(null,ids)}}
function DownloadFile({name,compact=false}){const f=files[name];return <a className={'ac-download '+(compact?'compact':'')} href={ROOT+f.file} download><Download size={18}/><span><strong>{f.label}</strong>{!compact&&<small>{f.detail}</small>}</span><span className="ac-file-type">{f.file.endsWith('.zip')?'ZIP':f.file.split('.').pop().toUpperCase()}</span></a>}
function TextCopy({text,label='복사',id}){const [state,setState]=useState('');const timer=useRef();useEffect(()=>()=>clearTimeout(timer.current),[]);useEffect(()=>setState(''),[text]);return <div className="ac-copy-action"><button type="button" className="ac-copy" onClick={async()=>{try{await navigator.clipboard.writeText(text);setState('done');clearTimeout(timer.current);timer.current=setTimeout(()=>setState(''),1800)}catch{setState('error');document.getElementById(id)?.focus()}}}>{state==='done'?<Check size={16}/>:<Copy size={16}/>}<span>{state==='done'?'복사 완료':label}</span></button><span className="ac-copy-status" role="status">{state==='error'?'복사가 허용되지 않았어요. 아래 내용을 직접 선택해 복사해 주세요.':''}</span></div>}
function saveText(text,name){const url=URL.createObjectURL(new Blob([text+'\n'],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function AgenticPractice(){
 const [saved]=useState(initial);const [current,setCurrent]=useState(()=>resolveStep(location.hash,ids,saved.current));const [done,setDone]=useState(saved.done);const [reset,setReset]=useState(false);const [storageError,setStorageError]=useState(false);
 const [team,setTeam]=useState(''),[project,setProject]=useState('');const heading=useRef();const index=ids.indexOf(current),step=steps[index];
 const valid=destinationValid(team,project);const prompt=step.prompt?fillPrompt(step.prompt,team,project):'';
 useEffect(()=>{const update=()=>setCurrent(now=>resolveStep(location.hash,ids,now));addEventListener('hashchange',update);addEventListener('popstate',update);return()=>{removeEventListener('hashchange',update);removeEventListener('popstate',update)}},[]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify({done,current}));setStorageError(false)}catch{setStorageError(true)}},[done,current]);
 function go(id,event){if(event&&(event.metaKey||event.ctrlKey||event.shiftKey||event.altKey))return;event?.preventDefault();history.pushState(null,'','#'+id);setCurrent(id);setReset(false);requestAnimationFrame(()=>{heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView({block:'start',behavior:'instant'})})}
 function mark(){setDone(now=>now.includes(current)?now.filter(x=>x!==current):[...now,current])}
 const sample=step.sample==='skill'?data.skill:step.sample==='a'?data.inputA:step.sample==='b'?data.inputB:null;
 return <main id="main" className="ac-page">
  <header className="ac-intro"><div><div className="eyebrow">HANDS-ON · REUSE → BUILD → VERIFY → DEPLOY</div><h1>에이전틱 코딩 실습</h1><p>기존 Skill을 써 보고, 공공데이터 API로 나만의 Skill을 만드세요.<br/>이 페이지는 안내서입니다. 실행은 <strong>ChatGPT Work와 Vercel</strong>에서 진행합니다.</p><nav className="ac-concept-shortcuts" aria-label="개념 바로가기"><a href="#understand-basics" onClick={e=>go('understand-basics',e)}>Skill·MCP 큰 그림</a><a href="#understand-skill" onClick={e=>go('understand-skill',e)}>Skill 구성요소</a><a href="#understand-mcp" onClick={e=>go('understand-mcp',e)}>MCP 구성요소</a></nav><details className="ac-verification"><summary>이 자료의 실제 검수 범위</summary><p>{data.verification}</p></details></div><DownloadFile name="bundle"/></header>
  <details className="ac-start" open={current===ids[0]||current==='prepare'}><summary>{data.start.title}</summary><p>{data.start.intro}</p><div className="ac-start-path">{data.start.outcomes.map(o=><a key={o.step} href={'#'+o.step} onClick={e=>go(o.step,e)}><strong>{o.title}</strong><span>{o.text}</span></a>)}</div><p>{data.start.files}</p><p>{data.start.attach}</p></details>
  <div className="ac-layout">
   <aside className="ac-sidebar" aria-label="실습 진행"><div className="ac-progress-title"><strong>나의 실습 기록</strong><span>{done.length} / {steps.length}</span></div><progress value={done.length} max={steps.length} aria-label={`직접 확인한 단계 ${done.length}/${steps.length}`}/><p className="ac-progress-hint">완료는 직접 확인한 뒤 표시해 주세요.<br/>{storageError?'현재 브라우저에서는 기록을 저장할 수 없습니다.':'이 브라우저에만 저장됩니다.'}</p>
    <nav className="ac-step-nav" aria-label="에이전틱 코딩 단계">{steps.map((s,i)=><a key={s.id} href={'#'+s.id} aria-current={current===s.id?'step':undefined} onClick={e=>go(s.id,e)}><span className={'ac-step-number '+(done.includes(s.id)?'checked':'')}>{done.includes(s.id)?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><span><small>{s.group}</small>{s.title}</span></a>)}</nav>
    <label className="ac-mobile-select">단계 이동<select value={current} onChange={e=>go(e.target.value)}>{steps.map((s,i)=><option key={s.id} value={s.id}>{i+1}. {s.title}{done.includes(s.id)?' · 확인함':''}</option>)}</select></label>
    {!reset?<button type="button" className="ac-reset" onClick={()=>setReset(true)}><RotateCcw size={13}/>진행 기록 초기화</button>:<div className="ac-reset-confirm"><p>이 실습의 확인 기록만 지울까요?</p><button type="button" onClick={()=>{setDone([]);setReset(false);go(ids[0])}}>기록 지우기</button><button type="button" onClick={()=>setReset(false)}>취소</button></div>}
   </aside>
   <article className="ac-lesson" aria-labelledby="ac-step-title" key={step.id}>
    <div className="ac-step-kicker">STEP {String(index+1).padStart(2,'0')} <span>{step.group}</span></div><h2 id="ac-step-title" ref={heading} tabIndex={-1}>{step.title}</h2><p className="ac-goal">{step.goal}</p>
    {step.concept&&<div className="ac-concepts" aria-label="오늘 연결할 세 가지"><div><Puzzle/><strong>Skill</strong><p>반복해서 쓸 작업 절차</p><small>공공데이터 → 검증한 정보</small></div><ArrowRight className="ac-flow-arrow"/><div><Link2/><strong>MCP</strong><p>외부 도구로 이어 주는 연결</p><small>Vercel 조회·배포 도구</small></div><ArrowRight className="ac-flow-arrow"/><div><Rocket/><strong>Deployment</strong><p>파일을 실제 주소에서 열기</p><small>Preview 확인 → 수정</small></div></div>}
    {step.lesson&&<AgenticConceptLesson name={step.lesson}/>}
    <div className="ac-location"><Monitor size={19}/><div><strong>어디서 하나요?</strong><span>{step.where}</span></div></div>
    {step.handoff&&<p className="ac-handoff"><strong>요청하기 전에</strong>{step.handoff}</p>}
    {step.routes&&<nav className="ac-routes" aria-label="내 결과에 맞는 경로"><strong>내 결과에 맞게 이어가기</strong>{step.routes.map(r=><a key={r.step} href={'#'+r.step} onClick={e=>go(r.step,e)}>{r.label}<ArrowRight size={16}/></a>)}<small>이동만으로 단계를 완료 처리하지 않습니다.</small></nav>}
    <section className="ac-actions" aria-label="실행 순서"><h3>이 순서로 따라 하세요</h3><ol>{step.actions.map((s,i)=><li key={s}><span>{i+1}</span><p>{s}</p></li>)}</ol></section>
    {step.explain&&<section className="ac-definitions"><h3>입력과 결과의 각 부분</h3><dl>{step.explain.map(p=><div key={p.term}><dt>{p.term}</dt><dd><p>{p.role}</p><code>{p.example}</code></dd></div>)}</dl></section>}
    {step.links&&<nav className="ac-lab-links" aria-label="이번 단계 참고 링크">{step.links.map(l=><a key={l.url} href={l.url} target="_blank" rel="noopener noreferrer">{l.label}<ArrowUpRight size={16}/></a>)}</nav>}
    {step.downloads&&<section className="ac-resources"><h3><FolderOpen size={18}/>이번 단계 파일</h3><div>{step.downloads.map(name=><DownloadFile key={name} name={name}/>)}</div>{step.id==='prepare'&&<p>선택 다운로드입니다. ZIP을 풀고 READ_ME.md부터 텍스트 편집기로 열면 됩니다. 웹 안내와 요청문만 사용해도 됩니다.</p>}</section>}
    {sample&&<details className="ac-example"><summary>{step.sample==='skill'?'Skill 본문 살펴보기':'입력 '+step.sample.toUpperCase()+' 내역 · 아래 요청문에 포함되어 있어요'}<FileText size={17}/></summary><div><TextCopy text={sample} label={step.sample==='skill'?'Skill 예시 복사':'입력 전체 복사'} id="ac-sample"/><textarea id="ac-sample" aria-label="예시 원문" value={sample} readOnly rows={Math.min(12,sample.split('\n').length+1)}/><p>{step.sample==='skill'?'설명용 예시입니다. 파일을 받는 것과 Skill을 생성·설치하는 것은 다릅니다.':'별도 전송하지 않아도 됩니다. 아래 요청문에 검색어와 결과 수가 포함돼 있습니다.'}</p></div></details>}
    {step.setting&&<details className="ac-optional"><summary>선택 경로: 데스크톱에서 직접 MCP 서버 설정하기</summary><p>아래는 웹 플러그인 설치와 별개인 수동 설정입니다. 데스크톱에 MCP servers 메뉴가 있는 환경에서만 사용하세요.</p><PracticeFieldRoles kind="settings"/>
    <section className="ac-mcp-settings"><h3>서버 설정값</h3><dl><div><dt>Name</dt><dd>vercel</dd></div><div><dt>Type</dt><dd>Streamable HTTP</dd></div><div><dt>URL</dt><dd><code>https://mcp.vercel.com</code><TextCopy text="https://mcp.vercel.com" label="주소 복사"/></dd></div></dl><div className="ac-setting-flow">Save <ArrowRight/> Restart <ArrowRight/> Authenticate <ArrowRight/> /mcp</div><p>로그인과 권한 허용은 Vercel 인증 창에서 진행합니다. 설정 파일을 직접 작성할 필요는 없습니다.</p></section></details>}
    {step.destination&&<PracticeFieldRoles kind="deployment"/>}
    {step.destination&&<fieldset className="ac-destination"><legend>나의 배포 대상</legend><p>앞 단계의 조회 결과를 보고 입력하세요. 요청문에만 반영하며 서버로 전송하지 않습니다.</p><div><label>팀 ID 또는 slug<input value={team} onChange={e=>setTeam(e.target.value)} autoComplete="off" spellCheck={false} maxLength={100} placeholder="조회 결과의 team_… 또는 팀 slug"/></label><label>새 실습 프로젝트 이름<input value={project} onChange={e=>setProject(e.target.value)} autoComplete="off" spellCheck={false} maxLength={100} placeholder="예: heritage-myname"/></label></div><small>프로젝트 이름은 영문 소문자·숫자·하이픈, 2–100자입니다. 앞뒤 하이픈과 연속된 ---는 쓰지 않습니다.</small>{!valid&&<p className="ac-destination-notice">두 항목을 올바르게 입력하면 요청문 복사와 다운로드가 활성화됩니다.</p>}</fieldset>}
    {prompt&&<section className="ac-prompt" aria-label="보낼 요청문"><div className="ac-prompt-heading"><h3>{step.promptTitle||'복사해서 보낼 요청문'}</h3>{!step.destination||valid?<TextCopy text={prompt} label="요청문 복사" id="ac-prompt-text"/>:<button className="ac-copy" type="button" disabled><Copy size={16}/>대상 입력 후 복사</button>}</div><textarea id="ac-prompt-text" aria-label="요청문 원문" readOnly value={prompt} rows={Math.min(13,prompt.split('\n').length+1)}/><div className="ac-prompt-foot"><small>{step.id==='create-api-skill'?'Skills → Create → Create with chat에서 시작합니다.':step.id==='snapshot-recovery'?'기존 Skill Creator 대화에서 첨부와 함께 요청하세요.':['k-run','api-a','api-b'].includes(step.id)?'등록된 Skill의 Try in chat으로 열고 요청을 추가하세요.':'실행은 ChatGPT Work에서 직접 요청합니다.'}</small><button type="button" disabled={step.destination&&!valid} onClick={()=>saveText(prompt,`${String(index+1).padStart(2,'0')}-${step.id}-prompt.txt`)}><Download size={15}/>요청문 TXT 받기</button></div></section>}
    {step.followup&&<section className="ac-prompt" aria-label="저장 후 실행 요청"><div className="ac-prompt-heading"><h3>{step.followup.title}</h3><TextCopy text={step.followup.prompt} label="실행 요청 복사" id="ac-followup-text"/></div><p className="ac-followup-where">{step.followup.where}</p><textarea id="ac-followup-text" aria-label="저장 후 실행 요청문" value={step.followup.prompt} readOnly rows={7}/><div className="ac-prompt-foot"><small>새 대화의 입력창에 첨부 파일 이름과 Skill 이름이 보이는지 확인하세요.</small><button type="button" onClick={()=>saveText(step.followup.prompt,`${String(index+1).padStart(2,'0')}-${step.id}-run.txt`)}><Download size={15}/>실행 요청 TXT 받기</button></div></section>}
    {step.screens&&<section className="ac-evidence"><h3>화면에서 무엇을 확인하나요?</h3>{step.screens.map(f=><figure key={f.src}><a href={f.src} target="_blank" rel="noopener noreferrer" aria-label={f.caption+' · 큰 이미지 열기'}><img src={f.src} alt={f.alt} loading="lazy"/><span>크게 보기 ↗</span></a><figcaption>{f.caption}</figcaption></figure>)}</section>}
    <section className="ac-check"><h3><ListChecks size={20}/>이렇게 보이면 성공이에요</h3><ul>{step.check.map(s=><li key={s}><CheckCircle2 size={17}/>{s}</li>)}</ul></section>
    <details className="ac-trouble"><summary>막혔을 때 확인할 것</summary><p>{step.trouble}</p></details>
    <div className="ac-completion"><button type="button" className={'ac-mark '+(done.includes(current)?'is-done':'')} onClick={mark} aria-pressed={done.includes(current)}><CheckCircle2 size={18}/>{done.includes(current)?'확인한 단계 · 표시 취소':'성공 기준을 직접 확인했어요'}</button><p>이 표시는 학습 기록이며, 계정 연결이나 배포 성공을 자동 검사하지 않습니다.</p></div>
    <nav className="ac-pagination" aria-label="이전 다음 실습 단계">{index>0?<a href={'#'+ids[index-1]} onClick={e=>go(ids[index-1],e)}><ArrowLeft size={18}/><span>이전<strong>{steps[index-1].title}</strong></span></a>:<span/>}{index<steps.length-1?<a href={'#'+ids[index+1]} onClick={e=>go(ids[index+1],e)}><span>다음<strong>{steps[index+1].title}</strong></span><ArrowRight size={18}/></a>:<div className="ac-finish"><CheckCircle2 size={20}/><strong>확인한 결과와 남은 과제를 정리하세요.</strong><span>다음에는 자신의 반복 업무와 데이터로 바꿔 보세요.</span></div>}</nav>
    {step.id==='update'&&<details className="ac-optional"><summary>선택: 검토한 페이지를 production으로 게시하기</summary><p>Preview 실습을 마친 뒤 정식 게시가 필요할 때만 진행합니다. 아래 요청에서도 같은 팀과 프로젝트를 지정하고, 실제 접근 범위는 별도로 확인합니다.</p><textarea readOnly aria-label="선택 게시 요청문" value={fillPrompt('검토한 현재 파일을 정식으로 게시하겠습니다. Vercel MCP로 팀 {{TEAM}}, 프로젝트 {{PROJECT}}, target production에 같은 파일을 배포해 주세요. 실제 배포 ID와 URL, 접근 범위를 확인하고 보호 설정·커스텀 도메인은 자동으로 변경하지 마세요.',team,project)} rows={5}/></details>}
    <details className="ac-sources"><summary>설정이 달라졌다면 공식 안내 확인</summary><a href="https://learn.chatgpt.com/docs/build-skills" target="_blank" rel="noreferrer">OpenAI · Skills<ArrowUpRight size={14}/></a><a href="https://learn.chatgpt.com/docs/extend/mcp" target="_blank" rel="noreferrer">OpenAI · MCP 설정<ArrowUpRight size={14}/></a><a href="https://vercel.com/docs/agent-resources/vercel-mcp/tools" target="_blank" rel="noreferrer">Vercel · 배포 도구<ArrowUpRight size={14}/></a></details>
   </article>
  </div>
 </main>
}
